### PR TITLE
DCES-77: Moving cron settings to a configuration variable

### PR DESCRIPTION
**Pull request by tanovellino**
## What

[Link to story](https://dsdmoj.atlassian.net/browse/LASB-XXX)

This is a small change to move the scheduler cron settings to a configuration variable.

Note: It doesn't seem to be working on local docker, but will hopefully test in the `dev` container

## Checklist

Before you ask people to review this PR:

- [x] Tests should be passing: `./gradlew test`
- [x] Github should not be reporting conflicts; you should have recently run `git rebase main`.
- [x] Avoid mixing whitespace changes with code changes in the same commit. These make diffs harder to read and conflicts more likely.
- [x] You should have looked at the diff against main and ensured that nothing unexpected is included in your changes.
- [x] You should have checked that the commit messages say why the change was made.

### CODE REVIEW

**Review by vloruncg — APPROVED** [review]
Just a suggestion on the naming... "CRON_CONTRIB..." rather than "DCES_CRON_CRONTRIB..." maybe as the DCES prefix is arguably redundant.

**Comment by tanovellino** [comment]
> Just a suggestion on the naming... "CRON_CONTRIB..." rather than "DCES_CRON_CRONTRIB..." maybe as the DCES prefix is arguably redundant.

Yeah I agree. the only reason I used the prefix is because this variables are used inside the spring configuration tree and wanted to make sure they are optionals for ours. But I will take that into consideration is we end up using the variables in the end

**Comment by LAA-Dave-Edwards** [comment]
Can you also add configs for the other environments?

**Comment by tanovellino** [comment]
> Can you also add configs for the other environments?

will do that when we setup the other environments. Currently there are no values at all yet

**Pull request merged**
